# Generated by Django 3.0 on 2021-04-12 10:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailToAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('name', models.CharField(max_length=50, verbose_name='ism')),
                ('subject', models.CharField(max_length=200, verbose_name='mavzu')),
                ('message', models.CharField(max_length=700)),
                ('checked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'maktabga xat',
                'verbose_name_plural': 'maktabga xat',
            },
        ),
    ]
