# Generated by Django 3.0 on 2021-04-12 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_mailtoadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtoadmin',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
